# Generated by Django 3.1.7 on 2021-03-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.IntegerField(choices=[(1, 'Изображение создано'), (2, 'Изображение изменено'), (3, 'Изображение удалено')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='image_app.imagestorage')),
            ],
        ),
    ]
