# Generated by Django 3.1.7 on 2021-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История изменений', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
